<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mohammed_Arham" failures="1" tests="3" name="listner test" time="10.761" errors="0" timestamp="2025-04-14T11:37:06 EDT">
  <testcase classname="testnglisteners.ListenersTestCase1" name="logoTest" time="5.12"/>
  <testcase classname="testnglisteners.ListenersTestCase1" name="urlTest" time="0.034">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at testnglisteners.ListenersTestCase1.urlTest(ListenersTestCase1.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- urlTest -->
  <testcase classname="testnglisteners.ListenersTestCase1" name="titleTest" time="0.0">
    <skipped/>
  </testcase> <!-- titleTest -->
</testsuite> <!-- listner test -->
